### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bewisesh91** [Jindonglee/Node_1#1]
필수 요구 사항: 프로젝트 관리
- [x] 1. `.env` 파일을 이용해서 민감한 정보(DB 계정 정보, API Key 등)를 관리합니다.
- [x] 2. `.gitignore` 파일을 생성하여 `.env` 파일과 `node_modules` 폴더가 Github에 올라가지 않도록 설정합니다.
- [x] 3. `.prettierrc` 파일을 생성하여 일정한 코드 포맷팅을 유지할 수 있도록 설정합니다.

-----
필수 요구 사항: API 구현하기
 1. 상품 작성 API
- [x] 상품명, 작성 내용, 작성자명, 비밀번호를 **request**에서 전달 받기
- [x] 상품은 두 가지 상태, **판매 중(`FOR_SALE`)및 판매 완료(`SOLD_OUT`)** 를 가질 수 있습니다.
- [x] 상품 등록 시 기본 상태는 **판매 중(`FOR_SALE`)** 입니다.
2. 상품 목록 조회 API
- [x] 상품명, 작성자명, 상품 상태, 작성 날짜 조회하기
- [x] 상품 목록은 작성 날짜를 기준으로 **내림차순(최신순)** 정렬하기
3. 상품 상세 조회 API
- [x] 상품명, 작성 내용, 작성자명, 상품 상태, 작성 날짜 조회하기
4. 상품 정보 수정 API
- [x] 상품명, 작성 내용, 상품 상태, 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **수정**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기
5. 상품 삭제 API
- [x] 비밀번호를 **request**에서 전달받기
- [x] 수정할 상품과 비밀번호 일치 여부를 확인한 후, 동일할 때만 글이 **삭제**되게 하기
- [x] 선택한 상품이 존재하지 않을 경우, “상품 조회에 실패하였습니다." 메시지 반환하기

-----
필수 요구 사항
- [x] AWS EC2 배포

-----

모든 필수 요구 사항을 잘 구현하셨습니다.
또한, validate 로직을 구현하여 사용자의 입력 값을 확인하는 로직 역시 훌륭합니다.

일부 코드에 대해서 피드백을 드리자면, 
현재 database에 값을 저장하는 로직에서 객체를 생성할 때 Data라고 지정하고 있는데요.
schema에 맞는 적절한 값을 사용하는 것이 조금 더 좋을 것 같습니다.
보편적인 변수 명보다는 의도가 명확히 드러나는 변수 명이 좋은 변수 명이라고 생각해요.

추가로 구현해보면 좋을 것 같은 것은
현재 사용자의 password를 입력 값 그대로 비교하고 있는데
암호화 로직을 추가해보는 것을 도전해보면 좋을 것 같습니다.

그리고 짜잘한 것이지만 routes폴더에 prudcts.rotuer.js라고 오타가 있습니다.
수정해주면 좋을 것 같아요!
또한 커밋 이력도 prefix 신경써주시면 감사할 것 같습니다!

첫 번째 개인 과제인데 멋지게 잘하셨습니다.
고생하셨고 다음 과제도 화이팅입니다 👍

**Comment by Jindonglee** [comment]
상세한 피드백 감사드립니다!!
커밋 이력 prefix라는 것이 있는 줄 몰랐는데 알려주셔서 감사합니다.
변수선언할 때도 신경써서 하겠습니다.
그 암호화 로직에 대해서 질문드릴 것이 있는데요.
제가 node에서 암호화에 대해 찾아보니 여러가지 모듈이 있었습니다. 
crypto나 bcrypt등 모듈이 있었는데 암호를 해시화 해서 저장하고 match하면 함수를 실행하는 그런 것으로 이해했는데
그렇다면 몽고DB에 접속하는데 쓰는 password와 해시값을 db에 저장하고 불러오는 식으로 해야할까요?
제가 아는 것이 적어 자세하게 설명드리지 못해 죄송합니다.
어떤 방향으로 암호화 로직을 구현하면 좋을지 방향성을 주시면 감사하겠습니다.
저도 좀 더 찾아보고 고민해보겠습니다!

11:55 추가: 아 사용자 password 말씀하시는거였군요 저는 dbPassword인줄 알고.. 일단 한번 해보고 찾아뵙겠습니다.
